
# Generated by GPT
import multiprocessing

bind = "0.0.0.0:8000"  # Listen on all IPs, Port 8000
workers = multiprocessing.cpu_count() * 2 + 1  # Optimal worker count
worker_class = "uvicorn.workers.UvicornWorker"  # Use Uvicorn for ASGI
timeout = 120  # Request timeout (for long-running WebSockets)
loglevel = "info"  # Log verbosity level
accesslog = "-"  # Print access logs to console
errorlog = "-"  # Print error logs to console